### ISSUE TITLE
setting.value is not a function

### ISSUE THREAD

**Issue by bassterror** [danrahn/MarkerEditorForPlex#25]
Hi there, since earlier this morning, I believe after the latest update, I receive the following error when I try to run the container:
```
[INFO   ] EditorConfig    - Reading configuration... 
[CRITICAL] ServerCore      - setting.value is not a function 
[ERROR  ] ServerCore      - The server ran into an unexpected problem, exiting...
```

 - OS: [Synology DSM 7.2.1-69057 Update 5]
 - Version: 2.7.0 (latest)
 - Docker: 20.10.23, build 876964a
 - docker-compose: 
```
services:
  intro-editor-plex:
    image: danrahn/intro-editor-for-plex:latest
    container_name: introeditplex
    restart: unless-stopped
    #network_mode: bridge
    networks:
      - proxy
    ports:
      - 3233:3232
    volumes:
      - ./appdata:/Data
      - ../plex/appdata/Library/Application Support/Plex Media Server:/PlexDataDirectory
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Sofia
networks:
  proxy:
    external: true
```
 - config.json:
```
{
    "dataPath": "/PlexDataDirectory",
    "database": "/PlexDataDirectory/Plug-in Support/Databases/com.plexapp.plugins.library.db",
    "host": "0.0.0.0",
    "port": 3232,
    "logLevel": "Info",
    "features": {
        "autoOpen": false,
        "extendedMarkerStats": true,
        "previewThumbnails": true
    }
}
```
